import type {
  User, ActivationCode, Team, Project, Event, Announcement,
  Task, TimelineEntry, WatchListEntry, InventoryItem, InventoryLoan,
  Graduate, School,
} from '../types';

export const INITIAL_SCHOOLS: School[] = [
  { id: 'sch1', name: 'Anadolu Lisesi', abbreviation: '15tmz', city: 'İstanbul', directorName: 'Ahmet Korkmaz', isDefault: true },
  { id: 'sch2', name: 'Fen Lisesi', abbreviation: '34fen', city: 'Ankara', directorName: 'Fatma Demir' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    schoolId: 'sch1',
    studentNo: 'SA001',
    firstName: 'Admin',
    lastName: 'ALA',
    username: 'adminala',
    email: 'adminala@opays.edu',
    role: 'superadmin',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Yönetim', 'Sistem'],
    points: 0,
    createdAt: '2024-09-01T08:00:00Z',
  },
  {
    id: 'u0',
    schoolId: 'sch1',
    studentNo: 'DM001',
    firstName: 'Demo',
    lastName: 'Kullanıcı',
    username: 'demo',
    email: 'demo@opays.edu',
    role: 'demo',
    isBlacklisted: false,
    isActivated: true,
    skills: [],
    points: 0,
    createdAt: '2024-09-01T08:00:00Z',
  },
  {
    id: 'u2',
    schoolId: 'sch1',
    studentNo: 'ADM01',
    firstName: 'Okul',
    lastName: 'Admini',
    username: 'okuladmin',
    email: 'admin@anadolu.edu',
    role: 'admin',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Yönetim'],
    points: 0,
    createdAt: '2024-09-01T09:00:00Z',
  },
  {
    id: 'u3',
    schoolId: 'sch1',
    studentNo: 'T001',
    firstName: 'Ayşe',
    lastName: 'Kaya',
    username: 'ayse.kaya',
    email: 'ayse@anadolu.edu',
    phone: '5321112233',
    instagram: 'ayse.kaya.tech',
    role: 'tech_teacher',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Robotik', 'Python', 'Arduino'],
    bio: 'Teknoloji öğretmeni',
    points: 0,
    createdAt: '2024-09-01T09:00:00Z',
  },
  {
    id: 'u4',
    schoolId: 'sch1',
    studentNo: 'S003',
    firstName: 'Mehmet',
    lastName: 'Demir',
    username: 'mehmet.demir',
    email: 'mehmet@anadolu.edu',
    phone: '5321223344',
    instagram: 'mehmet.demir11',
    role: 'student',
    class: '11',
    section: 'A',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Yazılım', 'C++', 'ROS'],
    bio: 'RoboTech Alpha takım kaptanı',
    points: 350,
    createdAt: '2024-09-02T10:00:00Z',
  },
  {
    id: 'u5',
    schoolId: 'sch1',
    studentNo: 'S004',
    firstName: 'Zeynep',
    lastName: 'Arslan',
    username: 'zeynep.arslan',
    email: 'zeynep@anadolu.edu',
    phone: '5323334455',
    instagram: 'zeynep.arslannn',
    role: 'student',
    class: '11',
    section: 'B',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Tasarım', 'Mekatronik', 'CAD'],
    bio: 'Teknofest Aviators takım kaptanı',
    points: 300,
    createdAt: '2024-09-02T10:00:00Z',
  },
  {
    id: 'u6',
    schoolId: 'sch1',
    studentNo: 'S005',
    firstName: 'Ali',
    lastName: 'Yılmaz',
    username: 'ali.yilmaz',
    email: 'ali@anadolu.edu',
    phone: '5324445566',
    instagram: 'ali.yilmaz10',
    role: 'student',
    class: '10',
    section: 'A',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Mekanik', '3D Yazıcı'],
    points: 200,
    createdAt: '2024-09-03T11:00:00Z',
  },
  {
    id: 'u7',
    schoolId: 'sch1',
    studentNo: 'S006',
    firstName: 'Elif',
    lastName: 'Şahin',
    username: 'elif.sahin',
    email: 'elif@anadolu.edu',
    phone: '5325556677',
    instagram: 'elif.sahin.design',
    role: 'student',
    class: '10',
    section: 'B',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Tasarım', 'Figma'],
    points: 150,
    createdAt: '2024-09-03T11:30:00Z',
  },
  {
    id: 'u8',
    schoolId: 'sch1',
    studentNo: 'S007',
    firstName: 'Can',
    lastName: 'Özkan',
    username: 'can.ozkan',
    email: 'can@anadolu.edu',
    role: 'student',
    class: '12',
    section: 'A',
    isBlacklisted: false,
    isActivated: true,
    skills: [],
    points: 50,
    createdAt: '2024-09-04T09:00:00Z',
  },
  {
    id: 'u9',
    schoolId: 'sch1',
    studentNo: 'T002',
    firstName: 'Selin',
    lastName: 'Yıldız',
    username: 'selin.yildiz',
    email: 'selin@anadolu.edu',
    role: 'branch_teacher',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Matematik', 'Fizik'],
    points: 0,
    createdAt: '2024-09-01T08:30:00Z',
  },
  {
    id: 'u10',
    schoolId: 'sch1',
    studentNo: 'S008',
    firstName: 'Deniz',
    lastName: 'Aktaş',
    username: 'deniz.aktas',
    email: 'deniz@anadolu.edu',
    phone: '5326667788',
    instagram: 'deniz.aktas12',
    role: 'student',
    class: '12',
    section: 'B',
    isBlacklisted: false,
    isActivated: true,
    skills: ['Web Geliştirme'],
    points: 250,
    createdAt: '2024-09-04T10:00:00Z',
  },
];

export const INITIAL_CODES: ActivationCode[] = [
  { code: '2026-15tmz-47382', schoolId: 'sch1', studentNo: 'S009', studentName: 'Ahmet Yılmaz', class: '9', section: 'A', isUsed: false, createdAt: '2024-09-01T00:00:00Z' },
  { code: '2026-15tmz-61924', schoolId: 'sch1', studentNo: 'S010', studentName: 'Fatma Çelik', class: '9', section: 'B', isUsed: false, createdAt: '2024-09-01T00:00:00Z' },
  { code: '2026-15tmz-35817', schoolId: 'sch1', studentNo: 'S011', studentName: 'Burak Aydın', class: '10', section: 'A', isUsed: false, createdAt: '2024-09-01T00:00:00Z' },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 't1',
    schoolId: 'sch1',
    name: 'RoboTech Alpha',
    type: 'robotics',
    captainId: 'u4',
    members: ['u4', 'u6'],
    description: 'Okul robotik takımı. Otonom sistemler ve yapay zeka odaklı projeler geliştiriyoruz.',
    logoInitials: 'RA',
    logoColor: 'from-cyan-500 to-blue-600',
    socialMedia: { instagram: '@roboteachalpha', twitter: '@roboteachalpha' },
    isRecruiting: true,
    applications: [
      { userId: 'u7', note: 'Tasarım konusunda katkı sağlamak istiyorum.', status: 'pending', appliedAt: '2026-04-20T10:00:00Z' },
    ],
    news: [
      { id: 'tn1', teamId: 't1', title: 'Bölgesel Şampiyonaya Katıldık!', content: 'RoboTech Alpha olarak İstanbul Bölgesel Robotik Şampiyonasına katıldık ve 2. olduk. Tüm takım üyelerimizi tebrik ediyoruz.', createdAt: '2026-04-01T00:00:00Z' },
    ],
    achievements: [
      { id: 'ta1', teamId: 't1', title: 'Bölgesel 2.lik', description: 'İstanbul Bölgesel Robotik Şampiyonası 2025', date: '2025-11-15', type: 'achievement' },
    ],
    createdAt: '2024-09-05T00:00:00Z',
  },
  {
    id: 't2',
    schoolId: 'sch1',
    name: 'Teknofest Aviators',
    type: 'teknofest',
    captainId: 'u5',
    members: ['u5', 'u7'],
    description: 'Teknofest insansız hava araçları kategorisinde yarışıyoruz. Drone tasarım ve uçuş sistemleri.',
    logoInitials: 'TA',
    logoColor: 'from-orange-500 to-red-600',
    socialMedia: { instagram: '@teknofest_aviators' },
    isRecruiting: false,
    applications: [],
    news: [],
    achievements: [
      { id: 'ta2', teamId: 't2', title: 'TechCo Sponsorluğu', description: 'TechCo firması takımımıza ekipman sponsorluğu verdi.', date: '2025-12-01', type: 'sponsor' },
    ],
    createdAt: '2024-09-06T00:00:00Z',
  },
  {
    id: 't3',
    schoolId: 'sch1',
    name: 'İnovasyon Kulübü',
    type: 'other',
    captainId: 'u4',
    members: ['u4'],
    description: 'Okul genelinde inovasyon ve girişimcilik etkinlikleri düzenleyen kulüp.',
    logoInitials: 'İK',
    logoColor: 'from-purple-500 to-indigo-600',
    socialMedia: {},
    isRecruiting: true,
    applications: [],
    news: [],
    achievements: [],
    createdAt: '2024-10-01T00:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p1',
    schoolId: 'sch1',
    teamId: 't1',
    title: 'Otonom Labirent Çözücü',
    description: 'ROS tabanlı otonom navigasyon sistemi. Labirent içinde engel algılama ve en kısa yol hesaplama algoritması kullanır.',
    goal: 'Karmaşık ortamlarda engel tanıyıp haritalayabilen otonom bir robot geliştirmek.',
    method: 'LiDAR sensörleri ve Dijkstra algoritması kullanılarak yol planlama yapılmakta, ROS frameworkü üzerinde çalışmaktadır.',
    status: 'in_progress',
    technologies: ['ROS', 'Python', 'OpenCV', 'Arduino', 'LiDAR'],
    contributors: ['u4', 'u6'],
    isVisible: true,
    isApproved: true,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'p2',
    schoolId: 'sch1',
    teamId: 't2',
    title: 'Teslimat Drone v2',
    description: 'GPS güdümlü otonom teslimat dronu. İkinci versiyon; ağırlık kapasitesi ve uçuş süresi iyileştirildi.',
    goal: 'İnsan erişiminin güç olduğu bölgelere kargo teslimatı yapabilen otonom drone sistemi geliştirmek.',
    method: 'ArduPilot yazılımı ve GPS/IMU sensörleri kullanılarak otonom navigasyon sağlanmaktadır.',
    status: 'completed',
    technologies: ['ArduPilot', 'Mission Planner', 'C++', 'Python', 'CAD'],
    contributors: ['u5', 'u7'],
    isVisible: true,
    isApproved: true,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2025-03-20T00:00:00Z',
  },
  {
    id: 'p3',
    schoolId: 'sch1',
    teamId: 't1',
    title: 'Akıllı Servis Robotu',
    description: 'Okul koridorlarında çalışacak yardımcı servis robotu. Ses tanıma ve yüz tanıma özellikleri entegre edilecek.',
    goal: 'Okul çalışanlarına yardımcı olacak yön gösteren ve bilgi sağlayan servis robotu geliştirmek.',
    method: 'TensorFlow ile eğitilmiş model, Raspberry Pi üzerinde çalışacak ve motor kontrolü Arduino ile yapılacak.',
    status: 'design',
    technologies: ['Python', 'TensorFlow', 'Raspberry Pi', 'Arduino'],
    contributors: ['u4'],
    isVisible: false,
    isApproved: false,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-04-15T00:00:00Z',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'e1',
    schoolId: 'sch1',
    title: 'Bölgesel Robotik Şampiyonası',
    type: 'competition',
    date: '2026-05-15T09:00:00Z',
    location: 'İstanbul Kongre Merkezi',
    description: 'Bölge genelinde 40+ takımın katıldığı robotik şampiyonası.',
    participants: ['u4', 'u6'],
    isPublic: true,
    createdBy: 'u1',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'e2',
    schoolId: 'sch1',
    title: 'Teknofest 2026',
    type: 'competition',
    date: '2026-09-20T08:00:00Z',
    location: 'Ankara',
    description: "Türkiye'nin en büyük teknoloji festivali.",
    participants: ['u5', 'u7'],
    isPublic: true,
    createdBy: 'u1',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'e3',
    schoolId: 'sch1',
    title: 'Takım Toplantısı — Bahar Planlaması',
    type: 'meeting',
    date: '2026-04-20T14:00:00Z',
    location: 'Robotik Lab',
    description: 'Bahar dönemi proje ve etkinlik planlaması.',
    participants: ['u4', 'u5', 'u6', 'u7'],
    isPublic: false,
    createdBy: 'u3',
    createdAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'e4',
    schoolId: 'sch1',
    title: 'Python Workshopu',
    type: 'workshop',
    date: '2026-05-05T15:00:00Z',
    location: 'Bilgisayar Lab',
    description: 'Robotik uygulamalar için Python programlama eğitimi.',
    participants: ['u6', 'u7'],
    isPublic: true,
    createdBy: 'u3',
    createdAt: '2026-04-12T00:00:00Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a1',
    schoolId: 'sch1',
    title: 'TOBB Yarışması Katılım',
    content: 'Projeler Bilim Teknoloji Koordinatörlüğü ve Öğrenci Başkanlığı tarafından seçilecektir. Başvurular 30 Nisan\'a kadar devam etmektedir. Proje özetinizi ve takım bilgilerinizi koordinatörlüğe iletiniz.',
    priority: 'medium',
    authorId: 'u1',
    createdAt: '2026-04-18T10:00:00Z',
  },
  {
    id: 'a2',
    schoolId: 'sch1',
    title: 'Teknofest 2026 Kayıt Açık',
    content: 'Teknofest 2026 kategorilerine kayıt açılmıştır. Takımlar 30 Mayıs\'a kadar başvurmak zorundadır. İHA, Robotik, Yapay Zeka ve Siber Güvenlik kategorilerinde yarışabilirsiniz.',
    priority: 'urgent',
    authorId: 'u1',
    createdAt: '2026-04-15T09:00:00Z',
  },
  {
    id: 'a3',
    schoolId: 'sch1',
    title: 'Yeni Robotik Lab Ekipmanları',
    content: 'Yeni 3D yazıcılar ve CNC makineleri geldi. Eğitim seansları önümüzdeki hafta başlıyor.',
    priority: 'low',
    authorId: 'u3',
    createdAt: '2026-04-15T08:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task1',
    schoolId: 'sch1',
    title: 'Teknofest 2026 Başvuru Dosyası Hazırlama',
    description: 'Teknofest 2026 için gerekli tüm belgelerin hazırlanması ve sisteme yüklenmesi.',
    type: 'organization',
    status: 'open',
    applicants: [],
    createdBy: 'u1',
    createdAt: '2026-04-16T00:00:00Z',
  },
  {
    id: 'task2',
    schoolId: 'sch1',
    title: 'Robotik Lab Web Sitesi Güncelleme',
    description: 'Okul robotik laboratuvarının web sitesine yeni proje ve etkinlik fotoğraflarının eklenmesi.',
    type: 'technical',
    status: 'open',
    applicants: [
      { userId: 'u7', note: 'Web tasarım konusunda deneyimim var.', status: 'pending', appliedAt: '2026-04-20T11:00:00Z' },
    ],
    createdBy: 'u3',
    createdAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'task3',
    schoolId: 'sch1',
    title: 'Bahar Fuarı Stant Tasarımı',
    description: 'Okul bahar fuarı için OPAYS ve robotik takımlarının tanıtım stantı tasarlanması.',
    type: 'design',
    status: 'in_progress',
    assignedTo: 'u7',
    applicants: [
      { userId: 'u7', note: 'Figma ile tasarım yapabilirim.', status: 'approved', appliedAt: '2026-04-14T09:00:00Z' },
    ],
    createdBy: 'u3',
    createdAt: '2026-04-13T00:00:00Z',
  },
  {
    id: 'task4',
    schoolId: 'sch1',
    title: 'Yeni Üye Oryantasyon Rehberi',
    description: 'Takımlara katılan yeni öğrenciler için oryantasyon rehberi hazırlanması.',
    type: 'organization',
    status: 'closed',
    applicants: [],
    createdBy: 'u1',
    createdAt: '2026-04-10T00:00:00Z',
  },
];

export const INITIAL_TIMELINE: TimelineEntry[] = [
  { id: 'tl1', userId: 'u4', type: 'team', referenceId: 't1', title: "RoboTech Alpha'ya Katıldı", description: 'Takım kaptanı olarak atandı.', isVerified: true, date: '2024-09-05T00:00:00Z' },
  { id: 'tl2', userId: 'u4', type: 'project', referenceId: 'p1', title: 'Otonom Labirent Çözücü — Başladı', description: 'Proje tasarım aşaması başlatıldı.', isVerified: true, date: '2025-01-15T00:00:00Z' },
  { id: 'tl3', userId: 'u4', type: 'achievement', referenceId: 'ta1', title: 'Bölgesel 2.lik Ödülü', description: 'İstanbul Bölgesel Robotik Şampiyonası 2025', isVerified: true, date: '2025-11-15T00:00:00Z' },
  { id: 'tl4', userId: 'u5', type: 'team', referenceId: 't2', title: "Teknofest Aviators'a Katıldı", description: 'Takım kaptanı olarak atandı.', isVerified: true, date: '2024-09-06T00:00:00Z' },
  { id: 'tl5', userId: 'u5', type: 'project', referenceId: 'p2', title: 'Teslimat Drone v2 — Tamamlandı', description: 'Proje başarıyla tamamlandı.', isVerified: true, date: '2025-03-20T00:00:00Z' },
  { id: 'tl6', userId: 'u6', type: 'team', referenceId: 't1', title: "RoboTech Alpha'ya Katıldı", description: 'Takım üyesi olarak eklendi.', isVerified: true, date: '2024-09-10T00:00:00Z' },
  { id: 'tl7', userId: 'u7', type: 'team', referenceId: 't2', title: "Teknofest Aviators'a Katıldı", description: 'Takım üyesi olarak eklendi.', isVerified: true, date: '2024-09-10T00:00:00Z' },
  { id: 'tl8', userId: 'u10', type: 'task', referenceId: 'task3', title: 'Stant Tasarımı Görevi Tamamlandı', description: 'Bahar fuarı stant tasarımı onaylandı.', isVerified: true, date: '2026-04-18T00:00:00Z' },
];

export const INITIAL_WATCHLIST: WatchListEntry[] = [
  { id: 'wl1', userId: 'u8', reason: 'Kulüp toplantılarına katılmama', addedBy: 'u3', date: '2026-03-15T10:00:00Z', isActive: true },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'inv1', schoolId: 'sch1', name: 'Arduino Uno', description: 'Arduino Uno R3 mikrodenetleyici', category: 'Elektronik', quantity: 15, available: 12, addedBy: 'u3', createdAt: '2025-09-01T00:00:00Z' },
  { id: 'inv2', schoolId: 'sch1', name: 'Raspberry Pi 4', description: 'Raspberry Pi 4 Model B 4GB RAM', category: 'Elektronik', quantity: 8, available: 6, addedBy: 'u3', createdAt: '2025-09-01T00:00:00Z' },
  { id: 'inv3', schoolId: 'sch1', name: 'LiDAR Sensör', description: 'RPLIDAR A1 360° Tarama', category: 'Sensör', quantity: 4, available: 4, addedBy: 'u3', createdAt: '2025-10-01T00:00:00Z' },
  { id: 'inv4', schoolId: 'sch1', name: 'Servo Motor', description: 'SG90 Mini Servo Motor', category: 'Motor', quantity: 30, available: 25, addedBy: 'u3', createdAt: '2025-09-01T00:00:00Z' },
  { id: 'inv5', schoolId: 'sch1', name: '3D Yazıcı Filament PLA', description: '1.75mm PLA Filament 1kg - Çeşitli Renkler', category: 'Malzeme', quantity: 10, available: 7, addedBy: 'u3', createdAt: '2025-09-01T00:00:00Z' },
];

export const INITIAL_LOANS: InventoryLoan[] = [
  { id: 'loan1', itemId: 'inv1', userId: 'u4', projectId: 'p1', quantity: 2, status: 'approved', note: 'Labirent çözücü için gerekli', requestedAt: '2026-01-10T00:00:00Z' },
  { id: 'loan2', itemId: 'inv4', userId: 'u4', projectId: 'p1', quantity: 3, status: 'approved', note: 'Robot hareket sistemi', requestedAt: '2026-01-10T00:00:00Z' },
];

export const INITIAL_GRADUATES: Graduate[] = [
  { userId: 'u8', schoolId: 'sch1', graduationYear: '2026', university: 'İTÜ', department: 'Bilgisayar Mühendisliği', shareProfile: true, contactInstagram: 'can.ozkan', contactEmail: 'can@gmail.com' },
];

export const PASSWORDS: Record<string, string> = {
  adminala: 'adminala',
  demo: 'demo',
  okuladmin: 'Admin123!',
  'ayse.kaya': 'Teacher123!',
  'mehmet.demir': 'Student123!',
  'zeynep.arslan': 'Student123!',
  'ali.yilmaz': 'Student123!',
  'elif.sahin': 'Student123!',
  'can.ozkan': 'Student123!',
  'selin.yildiz': 'Teacher123!',
  'deniz.aktas': 'Student123!',
};
